// <auto-generated />
using KwikMedicalServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KwikMedicalServer.Migrations
{
    [DbContext(typeof(KwikUserContext))]
    [Migration("20241124170920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("KwikMedicalServer.Data.KwikUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hospital")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KwikUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hospital = "Queen Margaret",
                            Password = "123",
                            Username = "Ben"
                        },
                        new
                        {
                            Id = 2,
                            Hospital = "",
                            Password = "123",
                            Username = "Ben"
                        },
                        new
                        {
                            Id = 3,
                            Hospital = "Kirkaldy",
                            Password = "123",
                            Username = "Agatha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
